env:
  global:
  - CC_TEST_REPORTER_ID=645c83c85822da1d09d8a99819c62c7a7c5f3bdd3cc4f771a433c456fb559261
language: node_js
node_js:
  - node
addons:
  chrome: stable
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: "Cl4e/WCw8OHIpqHz1xmeEETOFfvvH4QKfczB+f6oOE5yCl5Jk1uf6TTRIBV4VYgrE0hh7m9uWzqWSMmGP89BGOCz9zi5l6jrVS4RK5hKvt4nYDIvvpb/K/xeKj5wQ8164YlK2ogkMwoUD7Ee6xJqdFVGZOHr00hSNXYq5Bb1kW3xG97nIKqg9hrEwGBjxNIQW3aMAKg8H19IoWlZyHyv2Ryf1xKL81ydc8TWoz9kQqBxX4qAsJnyyCjWUUrI2njTNMnYghmRV6UkNsXkaFBZgl7d29d81uT3nk8NH5g+hlxsmn+1D7OvxiMxp8a1DaOlc8o2MHEALXEtcZP01sxf5Wa0AR6wq8yp0N9E7GTW7/tN932r8K4Xh+it/+hQBnGGpNKc6wkSzM0cfBT9thcrYhlfiRk9bpAvCqWJU9M53Yc9oKQgsYeR3+koU4ZFn1am5oBHawbhQ3b6mt+dyY/RA+nU7c9Qn+FBv6M7AYDrPZid+gSuufangIJBK/9IAyV+8l34xCDPZRPN2x/9z6R7qoMq69+gYYKVreO+LUJy1tIf2miUkm1HnkfEsI+GB2H2d7p1J0Wz6CPTdeC7fbarSAYIa1ZpOmX5eWnPRvi3QT0cCggA1dQOKBui79d7hhWmpKHff52G0FRVePw/Kr0wuB4UicKlWeHRj+V+50H4e9Y="
  app: travissend-it
  on:
    repo: Ibidapo/send-it
    branch: api-v1
