env:
  global:
  - CC_TEST_REPORTER_ID=645c83c85822da1d09d8a99819c62c7a7c5f3bdd3cc4f771a433c456fb559261
language: node_js
node_js:
- node
addons:
  chrome: stable
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: WwcrvjTqZwLSfIXmRTcH6rtNInJ5JBUS0oWH2YB89I6XOzagP7raS9mAWeDqlufgn71Y201U3Zi5duLTEJ5/6N6/LgwSpG4sAi+8OAilqu2o7GTg9vCHsiFlz9cmvUAm7eNR+vz+6xqChpgxLXGPNETTrd3otxM4pEiFAnJeg66uQAbuZpTqa7hwXtYyNtdiAXg+czF1CBVSDqdkn67qdUqtLX8grQ0tY+L1L0DqGu0YcohiEx/42KgRepkCZ7G2Ti3h1aWTSQcwYlBqQ8X8+wmOwe1d1/vRXLJuuU2FWb8JKrqySb+6HqwbzlUuFBhq7IvvDUCuMNsuCYwArKy90G0YD4trpIr/7mvfxleVNSmeMiZ+DvNnOqgyuz/XxsCvnmLuREzKswwLFCRzeudlPV1UTXFQwn3tEme1T0xHabycgcFmRyDOXZhbDcqUIiR6OnsKuP4k8fIEB31kCo8xlfMOXP3pIwtfDfRxxb6CQDEsSW5JPntAPLEZMIvbnpwzH+PurtVy802Nd16AWOVkC+2D+L4UAYsuqdcMzTwHCMInM3ZgZpYnho/2w449TSFhaUL4jaDZ1jR5I5PHcQs0OGhE2L2x0BEpRP/Zrpp6JRIebMls7s/YoJm5SBG2JtvR8le3s4O6X/hOEaA1nq+bwGrjU50vqGi+jYx71myj29w=
  app: travissend-it
  on:
    repo: Ibidapo/send-it
    branch: api-v1
