env:
  global:
  - CC_TEST_REPORTER_ID=645c83c85822da1d09d8a99819c62c7a7c5f3bdd3cc4f771a433c456fb559261
language: node_js
node_js:
  - node
addons:
  chrome: stable
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: "T8HIRKYzeb2MB//bqE4YTfDZYbXT87qzfkNAW6gP2Yl6BsjoZjY0bhmsGZ+dsHAUTozF5x9rdbd4YEmR4jFMKUi0rlryyAmOQVrhe6FX2PYVrk4UVFnPYQbaAjR+aRgmPSb2CEEcG7ANVkj06a2o1jxFtMD2hNReY3Thw8VZRut2CUt9BRmMsvS9wTDmxTiu7gTsq+uVvJ4rk5GrelHfcVdgT3ynNk9IJH20Xkx5i3dwYF6znELjayeykUXBGPdJpWEkeaSSMuuUc+7gf5EJn1cdxiEoUk2a/dZQ1DCcoRXgyhtEomUYkp/0wD9FqteyxXVTMc6swDPsbnCuDylANCnOl00CKQAgDkMBSQCUf4zBrC5zliSRhJLs2IpjHwnIQvH2JcngKZQZltKsmdO8kEpmQMr3sgbLPyiOC2gLBIt+lwSc3WEPhnK/sVrrou8eg16XcA10xBWW1yuwxSGGPm1Uy3v/lK5hLAalVk/wmNArjEuHWiwcrtCXMFpiqRGtC44P6p+gfC5OGI+ASrcaH4uaYBifw0wW2Li6vL8wAahMLyU9CuLmYgoZJVRy2lUHBFu53jrO+WxQHBeacRs2pReB9oWYl4119V2XzwswAtvYlSAp7cDOReP7EIGRzD3oxyXorV1fNtw7kTB3HNs82vm7OWu6162dSAXPRdt6bcw="
  app: travissend-it
  on:
    repo: Ibidapo/send-it
    branch: api-v1